on:
  push:
    branches:
      - master
name: publish packages
jobs:
  publish-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@creately'
      - run: npm ci
      - run: npm run publish-all
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
